In this guided project, we're going to learn how to:

    Import data into SQLite
    Design a normalized database schema
    Create tables for our schema
    Insert data into our schema
    
We will be working with a file of Major League Baseball games from Retrosheet.
http://www.retrosheet.org/

Retrosheet compiles detailed statistics on baseball games from the 1800s through to today.

Let's get started exploring the data by using pandas to read and explore the data. Setting the following options after you import pandas is recommendedâ€“ they will prevent the DataFrame output from being truncated, given the size of the main game log file:

In [1]:
import pandas as pd

game_log=pd.read_csv("game_log.csv")
park_codes=pd.read_csv("park_codes.csv")
person_codes=pd.read_csv("person_codes.csv")
team_codes=pd.read_csv("team_codes.csv")

/dataquest/system/env/python3/lib/python3.4/site-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (12,13,14,15,19,20,81,82,83,84,85,86,87,88,93,94,95,96,97,98,99,100,105,106,108,109,111,112,114,115,117,118,120,121,123,124,126,127,129,130,132,133,135,136,138,139,141,142,144,145,147,148,150,151,153,154,156,157,160) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [2]:
pd.set_option('max_columns', 180)
pd.set_option('max_rows', 200000)
pd.set_option('max_colwidth', 5000)

In [3]:
# Explorative Datenanalyse

In [4]:
game_log.columns

Index(['date', 'number_of_game', 'day_of_week', 'v_name', 'v_league',
       'v_game_number', 'h_name', 'h_league', 'h_game_number', 'v_score',
       ...
       'h_player_7_name', 'h_player_7_def_pos', 'h_player_8_id',
       'h_player_8_name', 'h_player_8_def_pos', 'h_player_9_id',
       'h_player_9_name', 'h_player_9_def_pos', 'additional_info',
       'acquisition_info'],
      dtype='object', length=161)

In [5]:
game_log.head()

,date,number_of_game,day_of_week,v_name,v_league,v_game_number,h_name,h_league,h_game_number,v_score,h_score,length_outs,day_night,completion,forefeit,protest,park_id,attendance,length_minutes,v_line_score,h_line_score,v_at_bats,v_hits,v_doubles,v_triples,v_homeruns,v_rbi,v_sacrifice_hits,v_sacrifice_flies,v_hit_by_pitch,v_walks,v_intentional_walks,v_strikeouts,v_stolen_bases,v_caught_stealing,v_grounded_into_double,v_first_catcher_interference,v_left_on_base,v_pitchers_used,v_individual_earned_runs,v_team_earned_runs,v_wild_pitches,v_balks,v_putouts,v_assists,v_errors,v_passed_balls,v_double_plays,v_triple_plays,h_at_bats,h_hits,h_doubles,h_triples,h_homeruns,h_rbi,h_sacrifice_hits,h_sacrifice_flies,h_hit_by_pitch,h_walks,h_intentional_walks,h_strikeouts,h_stolen_bases,h_caught_stealing,h_grounded_into_double,h_first_catcher_interference,h_left_on_base,h_pitchers_used,h_individual_earned_runs,h_team_earned_runs,h_wild_pitches,h_balks,h_putouts,h_assists,h_errors,h_passed_balls,h_double_plays,h_triple_plays,hp_umpire_id,hp_umpire_name,1b_umpire_id,1b_umpire_name,2b_umpire_id,2b_umpire_name,3b_umpire_id,3b_umpire_name,lf_umpire_id,lf_umpire_name,rf_umpire_id,rf_umpire_name,v_manager_id,v_manager_name,h_manager_id,h_manager_name,winning_pitcher_id,winning_pitcher_name,losing_pitcher_id,losing_pitcher_name,saving_pitcher_id,saving_pitcher_name,winning_rbi_batter_id,winning_rbi_batter_id_name,v_starting_pitcher_id,v_starting_pitcher_name,h_starting_pitcher_id,h_starting_pitcher_name,v_player_1_id,v_player_1_name,v_player_1_def_pos,v_player_2_id,v_player_2_name,v_player_2_def_pos,v_player_3_id,v_player_3_name,v_player_3_def_pos,v_player_4_id,v_player_4_name,v_player_4_def_pos,v_player_5_id,v_player_5_name,v_player_5_def_pos,v_player_6_id,v_player_6_name,v_player_6_def_pos,v_player_7_id,v_player_7_name,v_player_7_def_pos,v_player_8_id,v_player_8_name,v_player_8_def_pos,v_player_9_id,v_player_9_name,v_player_9_def_pos,h_player_1_id,h_player_1_name,h_player_1_def_pos,h_player_2_id,h_player_2_name,h_player_2_def_pos,h_player_3_id,h_player_3_name,h_player_3_def_pos,h_player_4_id,h_player_4_name,h_player_4_def_pos,h_player_5_id,h_player_5_name,h_player_5_def_pos,h_player_6_id,h_player_6_name,h_player_6_def_pos,h_player_7_id,h_player_7_name,h_player_7_def_pos,h_player_8_id,h_player_8_name,h_player_8_def_pos,h_player_9_id,h_player_9_name,h_player_9_def_pos,additional_info,acquisition_info
0,18710504,0,Thu,CL1,NaN,1,FW1,NaN,1,0,2,54.0,D,NaN,NaN,NaN,FOR01,200.0,120.0,000000000,010010000,30.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,6.0,1.0,NaN,-1.0,NaN,4.0,1.0,1.0,1.0,0.0,0.0,27.0,9.0,0.0,3.0,0.0,0.0,31.0,4.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,NaN,-1.0,NaN,3.0,1.0,0.0,0.0,0.0,0.0,27.0,3.0,3.0,1.0,1.0,0.0,boakj901,John Boake,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,paboc101,Charlie Pabor,lennb101,Bill Lennon,mathb101,Bobby Mathews,prata101,Al Pratt,NaN,NaN,NaN,NaN,prata101,Al Pratt,mathb101,Bobby Mathews,whitd102,Deacon White,2.0,kimbg101,Gene Kimball,4.0,paboc101,Charlie Pabor,7.0,allia101,Art Allison,8.0,white104,Elmer White,9.0,prata101,Al Pratt,1.0,sutte101,Ezra Sutton,5.0,carlj102,Jim Carleton,3.0,bassj101,John Bass,6.0,selmf101,Frank Sellman,5.0,mathb101,Bobby Mathews,1.0,foraj101,Jim Foran,3.0,goldw101,Wally Goldsmith,6.0,lennb101,Bill Lennon,2.0,caret101,Tom Carey,4.0,mince101,Ed Mincher,7.0,mcdej101,James McDermott,8.0,kellb105,Bill Kelly,9.0,NaN,Y
1,18710505,0,Fri,BS1,NaN,1,WS3,NaN,1,20,18,54.0,D,NaN,NaN,NaN,WAS01,5000.0,145.0,107000435,640113030,41.0,13.0,1.0,2.0,0.0,13.0,0.0,0.0,0.0,18.0,NaN,5.0,3.0,NaN,-1.0,NaN,12.0,1.0,6.0,6.0,1.0,0.0,27.0,13.0,10.0,1.0,2.0,0.0,49.0,14.0,2.0,0.0,0.0,11.0,0.0,0.0,0.0,10.0,NaN,2.0,1.0,NaN,-1.0,NaN,14.0,1.0,7.0,7.0,0.0,0.0,27.0,20.0,10.0,2.0,3.0,0.0,dobsh901,Henry Dobson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,wrigh101,Harry Wright,younn801,Nick Young,spala101,Al Spalding,braia102,Asa Brainard,NaN,NaN,NaN,NaN,spala101,Al Spalding,braia102,Asa Brainard,wrigg101,George Wright,6.0,barnr102,Ross Barnes,4.0,birdd102,Dave Birdsall,9.0,mcvec101,Cal McVey,2.0,wrigh101,Harry Wright,8.0,goulc101,Charlie Gould,3.0,schah101,Harry Schafer,5.0,conef101,Fred Cone,7.0,spala101,Al Spalding,1.0,watef102,Fred Waterman,5.0,forcd101,Davy Force,6.0,mille105,Everett Mills,3.0,allid101,Doug Allison,2.0,hallg101,George Hall,7.0,leona101,Andy Leonard,4.0,braia102,Asa Brainard,1.0,burrh101,Henry Burroughs,9.0,berth101,Henry Berthrong,8.0,HTBF,Y
2,18710506,0,Sat,CL1,NaN,2,RC1,NaN,1,12,4,54.0,D,NaN,NaN,NaN,RCK01,1000.0,140.0,610020003,010020100,49.0,11.0,1.0,1.0,0.0,8.0,0.0,0.0,0.0,0.0,NaN,1.0,0.0,NaN,-1.0,NaN,10.0,1.0,0.0,0.0,2.0,0.0,27.0,12.0,8.0,5.0,0.0,0.0,36.0,7.0,2.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,NaN,3.0,5.0,NaN,-1.0,NaN,5.0,1.0,3.0,3.0,1.0,0.0,27.0,12.0,13.0,3.0,0.0,0.0,mawnj901,J.H. Manny,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,paboc101,Charlie Pabor,hasts101,Scott Hastings,prata101,Al Pratt,fishc102,Cherokee Fisher,NaN,NaN,NaN,NaN,prata101,Al Pratt,fishc102,Cherokee Fisher,whitd102,Deacon White,2.0,kimbg101,Gene Kimball,4.0,paboc101,Charlie Pabor,7.0,allia101,Art Allison,8.0,white104,Elmer White,9.0,prata101,Al Pratt,1.0,sutte101,Ezra Sutton,5.0,carlj102,Jim Carleton,3.0,bassj101,John Bass,6.0,mackd101,Denny Mack,3.0,addyb101,Bob Addy,4.0,fishc102,Cherokee Fisher,1.0,hasts101,Scott Hastings,8.0,ham-r101,Ralph Ham,5.0,ansoc101,Cap Anson,2.0,sagep101,Pony Sager,6.0,birdg101,George Bird,7.0,stirg101,Gat Stires,9.0,NaN,Y
3,18710508,0,Mon,CL1,NaN,3,CH1,NaN,1,12,14,54.0,D,NaN,NaN,NaN,CHI01,5000.0,150.0,101403111,077000000,46.0,15.0,2.0,1.0,2.0,10.0,0.0,0.0,0.0,0.0,NaN,1.0,0.0,NaN,-1.0,NaN,7.0,1.0,6.0,6.0,0.0,0.0,27.0,15.0,11.0,6.0,0.0,0.0,43.0,11.0,2.0,0.0,0.0,8.0,0.0,0.0,0.0,4.0,NaN,2.0,1.0,NaN,-1.0,NaN,6.0,1.0,4.0,4.0,0.0,0.0,27.0,14.0,7.0,2.0,0.0,0.0,willg901,Gardner Willard,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,paboc101,Charlie Pabor,woodj106,Jimmy Wood,zettg101,George Zettlein,prata101,Al Pratt,NaN,NaN,NaN,NaN,prata101,Al Pratt,zettg101,George Zettlein,whitd102,Deacon White,2.0,kimbg101,Gene Kimball,4.0,paboc101,Charlie Pabor,7.0,allia101,Art Allison,8.0,white104,Elmer White,9.0,prata101,Al Pratt,1.0,sutte101,Ezra Sutton,5.0,carlj102,Jim Carleton,3.0,bassj101,John Bass,6.0,mcatb101,Bub McAtee,3.0,kingm101,Marshall King,8.0,hodec101,Charlie Hodes,2.0,woodj106,Jimmy Wood,4.0,simmj101,Joe Simmons,9.0,folet101,Tom Foley,7.0,duffe101,Ed Duffy,6.0,pinke101,Ed Pinkham,5.0,zettg101,George Zettlein,1.0,NaN,Y
4,18710509,0,Tue,BS1,NaN,2,TRO,NaN,1,9,5,54.0,D,NaN,NaN,NaN,TRO01,3250.0,145.0,000002232,101003000,46.0,17.0,4.0,1.0,0.0,6.0,0.0,0.0,0.0,2.0,NaN,0.0,1.0,NaN,-1.0,NaN,12.0,1.0,2.0,2.0,0.0,0.0,27.0,12.0,5.0,0.0,1.0,0.0,36.0,9.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,3.0,NaN,0.0,2.0,NaN,-1.0,NaN,7.0,1.0,3.0,3.0,1.0,0.0,27.0,11.0,7.0,3.0,0.0,0.0,leroi901,Isaac Leroy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,wrigh101,Harry Wright,pikel101,Lip Pike,spala101,Al Spalding,mcmuj101,John McMullin,NaN,NaN,NaN,NaN,spala101,Al Spalding,mcmuj101,John McMullin,wrigg101,George Wright,6.0,barnr102,Ross Barnes,4.0,birdd102,Dave Birdsall,9.0,mcvec101,Cal McVey,2.0,wrigh101,Harry Wright,8.0,goulc101,Charlie Gould,3.0,schah101,Harry Schafer,5.0,conef101,Fred Cone,7.0,spala101,Al Spalding,1.0,flync101,Clipper Flynn,9.0,mcgem101,Mike McGeary,2.0,yorkt101,Tom York,8.0,mcmuj101,John McMullin,1.0,kings101,Steve King,7.0,beave101,Edward Beavens,4.0,bells101,Steve Bellan,5.0,pikel101,Lip Pike,3.0,cravb101,Bill Craver,6.0,HTBF,Y

In [6]:
game_log.shape

(171907, 161)

In [7]:
game_log["v_player_1_def_pos"].unique()

array([ 2.,  6.,  3.,  9.,  5.,  1.,  8.,  7.,  4., nan, 10.])

In [8]:
game_log["v_league"].unique()

array([nan, 'NL', 'AA', 'UA', 'PL', 'AL', 'FL'], dtype=object)

In [9]:
game_log["h_league"].unique()

array([nan, 'NL', 'AA', 'UA', 'PL', 'AL', 'FL'], dtype=object)

game_log enthÃ¤lt Daten Ã¼ber jedes Baseball-Spiel beginnend ab dem Jahr 1871. Die Daten der Teams sind aufgeteilt in "h" und "v", was wahrscheinlich fÃ¼r "home" und "visitor" steht.

Enthalten sind auÃŸerdem durchnummerierten "defensive Positions", welche im Baseball festgelegten Positionen auf dem Spielfeld entsprechen (Pitcher, Catcher, First Base, etc.). Die Relevanz einer zehnten Position zu diesem Punkt der Datenanalyse noch unklar.

In [10]:
park_codes.head()

,park_id,name,aka,city,state,start,end,league,notes
0,ALB01,Riverside Park,NaN,Albany,NY,09/11/1880,05/30/1882,NL,TRN:9/11/80;6/15&9/10/1881;5/16-5/18&5/30/1882
1,ALT01,Columbia Park,NaN,Altoona,PA,04/30/1884,05/31/1884,UA,NaN
2,ANA01,Angel Stadium of Anaheim,Edison Field; Anaheim Stadium,Anaheim,CA,04/19/1966,NaN,AL,NaN
3,ARL01,Arlington Stadium,NaN,Arlington,TX,04/21/1972,10/03/1993,AL,NaN
4,ARL02,Rangers Ballpark in Arlington,The Ballpark in Arlington; Ameriquest Fl,Arlington,TX,04/11/1994,NaN,AL,NaN

In [11]:
park_codes.shape

(252, 9)

park_codes enthÃ¤lt Informationen Ã¼ber jedes Spielfeld/ Stadion.

In [12]:
person_codes.head()

         id     last   first player_debut mgr_debut coach_debut ump_debut
0  aardd001  Aardsma   David   04/06/2004       NaN         NaN       NaN
1  aaroh101    Aaron    Hank   04/13/1954       NaN         NaN       NaN
2  aarot101    Aaron  Tommie   04/10/1962       NaN  04/06/1979       NaN
3  aased001     Aase     Don   07/26/1977       NaN         NaN       NaN
4  abada001     Abad    Andy   09/10/2001       NaN         NaN       NaN

In [13]:
person_codes.shape

(20494, 7)

person_codes enthÃ¤lt Daten Ã¼ber alle mit dem Sport assoziierte Personen, die kÃ¶nnen Sportler, Manager, Coaches oder Schiedsrichter sein.

In [14]:
team_codes.head()

  team_id league  start   end       city         nickname franch_id  seq
0     ALT     UA   1884  1884    Altoona  Mountain Cities       ALT    1
1     ARI     NL   1998     0    Arizona     Diamondbacks       ARI    1
2     BFN     NL   1879  1885    Buffalo           Bisons       BFN    1
3     BFP     PL   1890  1890    Buffalo           Bisons       BFP    1
4     BL1    NaN   1872  1874  Baltimore         Canaries       BL1    1

Aus den bereits ausgegebenen Daten lassen sich durch Online-Recherche bereits einzelne Ligen identifizieren.
Als Recherche-Ansatz fÃ¼r die noch unbekannten Ligen "FL" und "AA" wird folgende Datenauswertung durchgefÃ¼hrt.

In [15]:
team_codes.loc[team_codes["league"]=="FL",["city","nickname","end"]].head(1)

         city   nickname   end
10  Baltimore  Terrapins  1915

FL:Federal League (nicht mehr existent)

In [16]:
team_codes.loc[team_codes["league"]=="AA",["city","nickname","end"]].head(1)

        city nickname   end
5  Baltimore  Orioles  1891

AA:American Association

Die einzelnen Ligen entsprechen nach Online-Recherche:
- NL:National League
- AL:American League
- UA:Union Association (nicht mehr existent)
- PL:Player's League (nicht mehr existent)
- FL:Federal League (nicht mehr existent)
- AA:American Association (nicht mehr existent)

In [17]:
!cat game_log_fields.txt

Field(s)  Meaning
    1     Date in the form "yyyymmdd"
    2     Number of game:
             "0" -- a single game
             "1" -- the first game of a double (or triple) header
                    including seperate admission doubleheaders
             "2" -- the second game of a double (or triple) header
                    including seperate admission doubleheaders
             "3" -- the third game of a triple-header
             "A" -- the first game of a double-header involving 3 teams
             "B" -- the second game of a double-header involving 3 teams
    3     Day of week  ("Sun","Mon","Tue","Wed","Thu","Fri","Sat")
  4-5     Visiting team and league
    6     Visiting team game number
          For this and the home team game number, ties are counted as
          games and suspended games are counted from the starting
          rather than the ending date.
  7-8     Home team and league
    9     Home team game number
10-11     Visiting and home team score (unquoted)
   12     Length of game in outs (unquoted).  A full 9-inning game would
          have a 54 in this field.  If the home team won without batting
          in the bottom of the ninth, this field would contain a 51.
   13     Day/night indicator ("D" or "N")
   14     Completion information.  If the game was completed at a
          later date (either due to a suspension or an upheld protest)
          this field will include:
             "yyyymmdd,park,vs,hs,len" Where
          yyyymmdd -- the date the game was completed
          park -- the park ID where the game was completed
          vs -- the visitor score at the time of interruption
          hs -- the home score at the time of interruption
          len -- the length of the game in outs at time of interruption
          All the rest of the information in the record refers to the
          entire game.
   15     Forfeit information:
             "V" -- the game was forfeited to the visiting team
             "H" -- the game was forfeited to the home team
             "T" -- the game was ruled a no-decision
   16     Protest information:
             "P" -- the game was protested by an unidentified team
             "V" -- a disallowed protest was made by the visiting team
             "H" -- a disallowed protest was made by the home team
             "X" -- an upheld protest was made by the visiting team
             "Y" -- an upheld protest was made by the home team
          Note: two of these last four codes can appear in the field
          (if both teams protested the game).
   17     Park ID
   18     Attendance (unquoted)
   19     Time of game in minutes (unquoted)
20-21     Visiting and home line scores.  For example:
             "010000(10)0x"
          Would indicate a game where the home team scored a run in
          the second inning, ten in the seventh and didn't bat in the
          bottom of the ninth.
22-38     Visiting team offensive statistics (unquoted) (in order):
             at-bats
             hits
             doubles
             triples
             homeruns
             RBI
             sacrifice hits.  This may include sacrifice flies for years
                prior to 1954 when sacrifice flies were allowed.
             sacrifice flies (since 1954)
             hit-by-pitch
             walks
             intentional walks
             strikeouts
             stolen bases
             caught stealing
             grounded into double plays
             awarded first on catcher's interference
             left on base
39-43     Visiting team pitching statistics (unquoted)(in order):
             pitchers used ( 1 means it was a complete game )
             individual earned runs
             team earned runs
             wild pitches
             balks
44-49     Visiting team defensive statistics (unquoted) (in order):
             putouts.  Note: prior to 1931, this may not equal 3 times
                the number of innings pitched.  Prior to that, no
                putout was awarded when a runner was declared out for
                being hit by a batted ball.
             assists
             errors
             passed balls
             double plays
             triple plays
50-66     Home team offensive statistics
67-71     Home team pitching statistics
72-77     Home team defensive statistics
78-79     Home plate umpire ID and name
80-81     1B umpire ID and name
82-83     2B umpire ID and name
84-85     3B umpire ID and name
86-87     LF umpire ID and name
88-89     RF umpire ID and name
          If any umpire positions were not filled for a particular game
          the fields will be "","(none)".
90-91     Visiting team manager ID and name
92-93     Home team manager ID and name
94-95     Winning pitcher ID and name
96-97     Losing pitcher ID and name
98-99     Saving pitcher ID and name--"","(none)" if none awarded
100-101   Game Winning RBI batter ID and name--"","(none)" if none
          awarded
102-103   Visiting starting pitcher ID and name
104-105   Home starting pitcher ID and name
106-132   Visiting starting players ID, name and defensive position,
          listed in the order (1-9) they appeared in the batting order.
133-159   Home starting players ID, name and defensive position
          listed in the order (1-9) they appeared in the batting order.
  160     Additional information.  This is a grab-bag of informational
          items that might not warrant a field on their own.  The field
          is alpha-numeric. Some items are represented by tokens such as:
             "HTBF" -- home team batted first.
             Note: if "HTBF" is specified it would be possible to see
             something like "01002000x" in the visitor's line score.
          Changes in umpire positions during a game will also appear in
          this field.  These will be in the form:
             umpchange,inning,umpPosition,umpid with the latter three
             repeated for each umpire.
          These changes occur with umpire injuries, late arrival of
          umpires or changes from completion of suspended games. Details
          of suspended games are in field 14.
  161     Acquisition information:
             "Y" -- we have the complete game
             "N" -- we don't have any portion of the game
             "D" -- the game was derived from box score and game story
             "P" -- we have some portion of the game.  We may be missing
                    innings at the beginning, middle and end of the game.

Missing fields will be NULL.


# Daten in Datenbank einlesen

Use DataFrame.to_sql() to create tables for each of our dataframes in a new SQLite database

In [18]:
import sqlite3 as sql

In [19]:
def run_command(c):
    with sql.connect("mlb.db") as conn:
        conn.isolation_level=None
        conn.execute(c)

In [20]:
def run_query(q):
    with sql.connect("mlb.db") as conn:
        return pd.read_sql(q, conn)

In [21]:
#game_log.to_sql("game_log",sql.connect("mlb.db"),index=False)

In [22]:
#run_command("alter table game_log add column game_id text")

In [23]:
run_query("select count(date) from game_log")

   count(date)
0       171907

In [24]:
run_query("select * from game_log limit 10")

,date,number_of_game,day_of_week,v_name,v_league,v_game_number,h_name,h_league,h_game_number,v_score,h_score,length_outs,day_night,completion,forefeit,protest,park_id,attendance,length_minutes,v_line_score,h_line_score,v_at_bats,v_hits,v_doubles,v_triples,v_homeruns,v_rbi,v_sacrifice_hits,v_sacrifice_flies,v_hit_by_pitch,v_walks,v_intentional_walks,v_strikeouts,v_stolen_bases,v_caught_stealing,v_grounded_into_double,v_first_catcher_interference,v_left_on_base,v_pitchers_used,v_individual_earned_runs,v_team_earned_runs,v_wild_pitches,v_balks,v_putouts,v_assists,v_errors,v_passed_balls,v_double_plays,v_triple_plays,h_at_bats,h_hits,h_doubles,h_triples,h_homeruns,h_rbi,h_sacrifice_hits,h_sacrifice_flies,h_hit_by_pitch,h_walks,h_intentional_walks,h_strikeouts,h_stolen_bases,h_caught_stealing,h_grounded_into_double,h_first_catcher_interference,h_left_on_base,h_pitchers_used,h_individual_earned_runs,h_team_earned_runs,h_wild_pitches,h_balks,h_putouts,h_assists,h_errors,h_passed_balls,h_double_plays,h_triple_plays,hp_umpire_id,hp_umpire_name,1b_umpire_id,1b_umpire_name,2b_umpire_id,2b_umpire_name,3b_umpire_id,3b_umpire_name,lf_umpire_id,lf_umpire_name,rf_umpire_id,rf_umpire_name,v_manager_id,v_manager_name,h_manager_id,h_manager_name,winning_pitcher_id,winning_pitcher_name,losing_pitcher_id,losing_pitcher_name,saving_pitcher_id,saving_pitcher_name,winning_rbi_batter_id,winning_rbi_batter_id_name,v_starting_pitcher_id,v_starting_pitcher_name,h_starting_pitcher_id,h_starting_pitcher_name,v_player_1_id,v_player_1_name,v_player_1_def_pos,v_player_2_id,v_player_2_name,v_player_2_def_pos,v_player_3_id,v_player_3_name,v_player_3_def_pos,v_player_4_id,v_player_4_name,v_player_4_def_pos,v_player_5_id,v_player_5_name,v_player_5_def_pos,v_player_6_id,v_player_6_name,v_player_6_def_pos,v_player_7_id,v_player_7_name,v_player_7_def_pos,v_player_8_id,v_player_8_name,v_player_8_def_pos,v_player_9_id,v_player_9_name,v_player_9_def_pos,h_player_1_id,h_player_1_name,h_player_1_def_pos,h_player_2_id,h_player_2_name,h_player_2_def_pos,h_player_3_id,h_player_3_name,h_player_3_def_pos,h_player_4_id,h_player_4_name,h_player_4_def_pos,h_player_5_id,h_player_5_name,h_player_5_def_pos,h_player_6_id,h_player_6_name,h_player_6_def_pos,h_player_7_id,h_player_7_name,h_player_7_def_pos,h_player_8_id,h_player_8_name,h_player_8_def_pos,h_player_9_id,h_player_9_name,h_player_9_def_pos,additional_info,acquisition_info,game_id
0,18710504,0,Thu,CL1,None,1,FW1,None,1,0,2,54.0,D,None,None,None,FOR01,200.0,120.0,000000000,010010000,30.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,None,6.0,1.0,None,-1.0,None,4.0,1.0,1.0,1.0,0.0,0.0,27.0,9.0,0.0,3.0,0.0,0.0,31.0,4.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,None,0.0,0.0,None,-1.0,None,3.0,1.0,0.0,0.0,0.0,0.0,27.0,3.0,3.0,1.0,1.0,0.0,boakj901,John Boake,None,None,None,None,None,None,None,None,None,None,paboc101,Charlie Pabor,lennb101,Bill Lennon,mathb101,Bobby Mathews,prata101,Al Pratt,None,None,None,None,prata101,Al Pratt,mathb101,Bobby Mathews,whitd102,Deacon White,2.0,kimbg101,Gene Kimball,4.0,paboc101,Charlie Pabor,7.0,allia101,Art Allison,8.0,white104,Elmer White,9.0,prata101,Al Pratt,1.0,sutte101,Ezra Sutton,5.0,carlj102,Jim Carleton,3.0,bassj101,John Bass,6.0,selmf101,Frank Sellman,5.0,mathb101,Bobby Mathews,1.0,foraj101,Jim Foran,3.0,goldw101,Wally Goldsmith,6.0,lennb101,Bill Lennon,2.0,caret101,Tom Carey,4.0,mince101,Ed Mincher,7.0,mcdej101,James McDermott,8.0,kellb105,Bill Kelly,9.0,None,Y,FW1187105040
1,18710505,0,Fri,BS1,None,1,WS3,None,1,20,18,54.0,D,None,None,None,WAS01,5000.0,145.0,107000435,640113030,41.0,13.0,1.0,2.0,0.0,13.0,0.0,0.0,0.0,18.0,None,5.0,3.0,None,-1.0,None,12.0,1.0,6.0,6.0,1.0,0.0,27.0,13.0,10.0,1.0,2.0,0.0,49.0,14.0,2.0,0.0,0.0,11.0,0.0,0.0,0.0,10.0,None,2.0,1.0,None,-1.0,None,14.0,1.0,7.0,7.0,0.0,0.0,27.0,20.0,10.0,2.0,3.0,0.0,dobsh901,Henry Dobson,None,None,None,None,None,None,None,None,None,None,wrigh101,Harry Wright,younn801,Nick Young,spala101,Al Spalding,braia102,Asa Brainard,None,None,None,None,spala101,Al Spalding,braia102,Asa Brainard,wrigg101,George Wright,6.0,barnr102,Ross Barnes,4.0,birdd102,Dave Birdsall,9.0,mcvec101,Cal McVey,2.0,wrigh101,Harry Wright,8.0,goulc101,Charlie Gould,3.0,schah101,Harry Schafer,5.0,conef101,Fred Cone,7.0,spala101,Al Spalding,1.0,watef102,Fred Waterman,5.0,forcd101,Davy Force,6.0,mille105,Everett Mills,3.0,allid101,Doug Allison,2.0,hallg101,George Hall,7.0,leona101,Andy Leonard,4.0,braia102,Asa Brainard,1.0,burrh101,Henry Burroughs,9.0,berth101,Henry Berthrong,8.0,HTBF,Y,WS3187105050
2,18710506,0,Sat,CL1,None,2,RC1,None,1,12,4,54.0,D,None,None,None,RCK01,1000.0,140.0,610020003,010020100,49.0,11.0,1.0,1.0,0.0,8.0,0.0,0.0,0.0,0.0,None,1.0,0.0,None,-1.0,None,10.0,1.0,0.0,0.0,2.0,0.0,27.0,12.0,8.0,5.0,0.0,0.0,36.0,7.0,2.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,None,3.0,5.0,None,-1.0,None,5.0,1.0,3.0,3.0,1.0,0.0,27.0,12.0,13.0,3.0,0.0,0.0,mawnj901,J.H. Manny,None,None,None,None,None,None,None,None,None,None,paboc101,Charlie Pabor,hasts101,Scott Hastings,prata101,Al Pratt,fishc102,Cherokee Fisher,None,None,None,None,prata101,Al Pratt,fishc102,Cherokee Fisher,whitd102,Deacon White,2.0,kimbg101,Gene Kimball,4.0,paboc101,Charlie Pabor,7.0,allia101,Art Allison,8.0,white104,Elmer White,9.0,prata101,Al Pratt,1.0,sutte101,Ezra Sutton,5.0,carlj102,Jim Carleton,3.0,bassj101,John Bass,6.0,mackd101,Denny Mack,3.0,addyb101,Bob Addy,4.0,fishc102,Cherokee Fisher,1.0,hasts101,Scott Hastings,8.0,ham-r101,Ralph Ham,5.0,ansoc101,Cap Anson,2.0,sagep101,Pony Sager,6.0,birdg101,George Bird,7.0,stirg101,Gat Stires,9.0,None,Y,RC1187105060
3,18710508,0,Mon,CL1,None,3,CH1,None,1,12,14,54.0,D,None,None,None,CHI01,5000.0,150.0,101403111,077000000,46.0,15.0,2.0,1.0,2.0,10.0,0.0,0.0,0.0,0.0,None,1.0,0.0,None,-1.0,None,7.0,1.0,6.0,6.0,0.0,0.0,27.0,15.0,11.0,6.0,0.0,0.0,43.0,11.0,2.0,0.0,0.0,8.0,0.0,0.0,0.0,4.0,None,2.0,1.0,None,-1.0,None,6.0,1.0,4.0,4.0,0.0,0.0,27.0,14.0,7.0,2.0,0.0,0.0,willg901,Gardner Willard,None,None,None,None,None,None,None,None,None,None,paboc101,Charlie Pabor,woodj106,Jimmy Wood,zettg101,George Zettlein,prata101,Al Pratt,None,None,None,None,prata101,Al Pratt,zettg101,George Zettlein,whitd102,Deacon White,2.0,kimbg101,Gene Kimball,4.0,paboc101,Charlie Pabor,7.0,allia101,Art Allison,8.0,white104,Elmer White,9.0,prata101,Al Pratt,1.0,sutte101,Ezra Sutton,5.0,carlj102,Jim Carleton,3.0,bassj101,John Bass,6.0,mcatb101,Bub McAtee,3.0,kingm101,Marshall King,8.0,hodec101,Charlie Hodes,2.0,woodj106,Jimmy Wood,4.0,simmj101,Joe Simmons,9.0,folet101,Tom Foley,7.0,duffe101,Ed Duffy,6.0,pinke101,Ed Pinkham,5.0,zettg101,George Zettlein,1.0,None,Y,CH1187105080
4,18710509,0,Tue,BS1,None,2,TRO,None,1,9,5,54.0,D,None,None,None,TRO01,3250.0,145.0,000002232,101003000,46.0,17.0,4.0,1.0,0.0,6.0,0.0,0.0,0.0,2.0,None,0.0,1.0,None,-1.0,None,12.0,1.0,2.0,2.0,0.0,0.0,27.0,12.0,5.0,0.0,1.0,0.0,36.0,9.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,3.0,None,0.0,2.0,None,-1.0,None,7.0,1.0,3.0,3.0,1.0,0.0,27.0,11.0,7.0,3.0,0.0,0.0,leroi901,Isaac Leroy,None,None,None,None,None,None,None,None,None,None,wrigh101,Harry Wright,pikel101,Lip Pike,spala101,Al Spalding,mcmuj101,John McMullin,None,None,None,None,spala101,Al Spalding,mcmuj101,John McMullin,wrigg101,George Wright,6.0,barnr102,Ross Barnes,4.0,birdd102,Dave Birdsall,9.0,mcvec101,Cal McVey,2.0,wrigh101,Harry Wright,8.0,goulc101,Charlie Gould,3.0,schah101,Harry Schafer,5.0,conef101,Fred Cone,7.0,spala101,Al Spalding,1.0,flync101,Clipper Flynn,9.0,mcgem101,Mike McGeary,2.0,yorkt101,Tom York,8.0,mcmuj101,John McMullin,1.0,kings101,Steve King,7.0,beave101,Edward Beavens,4.0,bells101,Steve Bellan,5.0,pikel101,Lip Pike,3.0,cravb101,Bill Craver,6.0,HTBF,Y,TRO187105090
5,18710511,0,Thu,CH1,None,2,CL1,None,4,18,10,48.0,D,None,V,None,CLE01,2500.0,120.0,12120534,01410004,41.0,15.0,1.0,3.0,3.0,10.0,0.0,0.0,0.0,8.0,None,1.0,0.0,None,-1.0,None,7.0,1.0,4.0,4.0,0.0,0.0,24.0,11.0,4.0,3.0,0.0,0.0,39.0,13.0,1.0,2.0,1.0,7.0,0.0,0.0,0.0,0.0,None,0.0,0.0,None,-1.0,None,5.0,2.0,10.0,10.0,2.0,0.0,24.0,7.0,5.0,2.0,0.0,0.0,haynj901,J.H. Haynie,None,None,None,None,None,None,None,None,None,None,woodj106,Jimmy Wood,paboc101,Charlie Pabor,zettg101,George Zettlein,prata101,Al Pratt,None,None,None,None,zettg101,George Zettlein,prata101,Al Pratt,mcatb101,Bub McAtee,3.0,kingm101,Marshall King,7.0,hodec101,Charlie Hodes,2.0,woodj106,Jimmy Wood,4.0,simmj101,Joe Simmons,8.0,folet101,Tom Foley,9.0,duffe101,Ed Duffy,6.0,pinke101,Ed Pinkham,5.0,zettg101,George Zettlein,1.0,whitd102,Deacon White,2.0,kimbg101,Gene Kimball,4.0,paboc101,Charlie Pabor,7.0,allia101,Art Allison,8.0,white104,Elmer White,9.0,prata101,Al Pratt,1.0,sutte101,Ezra Sutton,5.0,carlj102,Jim Carleton,3.0,bassj101,John Bass,6.0,None,Y,CL1187105110
6,18710513,0,Sat,WS3,None,2,CL1,None,5,12,8,54.0,D,None,None,None,CIN01,1200.0,150.0,141020004,004100012,42.0,9.0,2.0,0.0,0.0,5.0,0.0,0.0,0.0,1.0,None,1.0,1.0,None,-1.0,None,4.0,1.0,2.0,2.0,0.0,0.0,27.0,9.0,6.0,3.0,1.0,0.0,39.0,11.0,1.0,1.0,0.0,5.0,0.0,0.0,0.0,0.0,None,1.0,0.0,None,-1.0,None,4.0,1.0,3.0,3.0,3.0,0.0,27.0,6.0,8.0,1.0,0.0,0.0,drapj901,Doc Draper,None,None,None,None,None,None,None,None,None,None,younn801,Nick Young,paboc101,Charlie Pabor,braia102,Asa Brainard,prata101,Al Pratt,None,None,None,None,braia102,Asa Brainard,prata101,Al Pratt,watef102,Fred Waterman,2.0,forcd101,Davy Force,6.0,mille105,Everett Mills,3.0,glenj102,John Glenn,9.0,burrh101,Henry Burroughs,5.0,leona101,Andy Leonard,7.0,braia102,Asa Brainard,1.0,hallg101,George Hall,8.0,berth101,Henry Berthrong,4.0,whitd102,Deacon White,2.0,allia101,Art Allison,8.0,paboc101,Charlie Pabor,7.0,carlj102,Jim Carleton,3.0,kimbg101,Gene Kimball,4.0,prata101,Al Pratt,1.0,sutte101,Ezra Sutton,5.0,white104,Elmer White,9.0,bassj101,John Bass,6.0,None,Y,CL1187105130
7,18710513,0,Sat,CH1,None,3,FW1,None,2,14,5,54.0,D,None,None,None,FOR01,1500.0,105.0,053210012,200002001,45.0,17.0,5.0,2.0,0.0,10.0,0.0,0.0,0.0,1.0,None,1.0,2.0,None,-1.0,None,5.0,1.0,2.0,2.0,0.0,0.0,27.0,8.0,4.0,2.0,0.0,0.0,33.0,5.0,1.0,2.0,0.0,3.0,0.0,0.0,0.0,3.0,None,1.0,0.0,None,-1.0,None,4.0,1.0,6.0,6.0,0.0,0.0,27.0,8.0,7.0,3.0,0.0,0.0,haynj901,J.H. Haynie,None,None,None,None,None,None,None,None,None,None,woodj106,Jimmy Wood,lennb101,Bill Lennon,zettg101,George Zettlein,mathb101,Bobby Mathews,None,None,None,None,zettg101,George Zettlein,mathb101,Bobby Mathews,mcatb101,Bub McAtee,3.0,kingm101,Marshall King,8.0,hodec101,Charlie Hodes,2.0,woodj106,Jimmy Wood,4.0,simmj101,Joe Simmons,9.0,folet101,Tom Foley,7.0,duffe101,Ed Duffy,6.0,pinke101,Ed Pinkham,5.0,zettg101,George Zettlein,1.0,selmf101,Frank Sellman,5.0,mathb101,Bobby Mathews,1.0,foraj101,Jim Foran,3.0,goldw101,Wally Goldsmith,6.0,lennb101,Bill Lennon,2.0,caret101,Tom Carey,4.0,mince101,Ed Mincher,7.0,donnp101,Pete Donnelly,8.0,kellb105,Bill Kelly,9.0,None,Y,FW1187105130
8,18710515,0,Mon,WS3,None,3,FW1,None,3,6,12,54.0,D,None,None,None,FOR01,NaN,140.0,030100101,003300123,42.0,8.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,None,1.0,1.0,None,-1.0,None,10.0,1.0,4.0,4.0,0.0,0.0,27.0,13.0,5.0,6.0,0.0,0.0,49.0,20.0,5.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,None,1.0,1.0,None,-1.0,None,10.0,1.0,1.0,1.0,0.0,0.0,27.0,6.0,9.0,2.0,0.0,0.0,holls901,Sam Holley,None,None,None,None,None,None,None,None,None,None,younn801,Nick Young,lennb101,Bill Lennon,mathb101,Bobby Mathews,braia102,Asa Brainard,None,None,None,None,braia102,Asa Brainard,mathb101,Bobby Mathews,watef102,Fred Waterman,2.0,forcd101,Davy Force,6.0,mille105,Everett Mills,3.0,glenj102,John Glenn,9.0,burrh101,Henry Burroughs,5.0,leona101,Andy Leonard,7.0,braia102,Asa Brainard,1.0,hallg101,George Hall,8.0,berth101,Henry Berthrong,4.0,selmf101,Frank Sellman,5.0,mathb101,Bobby Mathews,1.0,foraj101,Jim Foran,3.0,goldw101,Wally Goldsmith,6.0,lennb101,Bill Lennon,2.0,caret101,Tom Carey,4.0,mince101,Ed Mincher,7.0,donnp101,Pete Donnelly,9.0,kellb105,Bill Kelly,8.0,None,Y,FW1187105150
9,18710516,0,Tue,TRO,None,2,BS1,None,3,29,14,54.0,D,None,None,None,BOS01,2500.0,NaN,302604(11)30,610020221,64.0,26.0,3.0,1.0,0.0,26.0,0.0,0.0,0.0,2.0,None,0.0,3.0,None,-1.0,None,10.0,1.0,4.0,4.0,0.0,0.0,27.0,11.0,8.0,3.0,3.0,0.0,43.0,13.0,3.0,0.0,0.0,9.0,0.0,0.0,0.0,4.0,None,1.0,3.0,None,-1.0,None,6.0,1.0,10.0,10.0,0.0,0.0,27.0,17.0,15.0,2.0,1.0,0.0,rogem901,Mort Rogers,None,None,None,None,None,None,None,None,None,None,pikel101,Lip Pike,wrigh101,Harry Wright,mcmuj101,John McMullin,spala101,Al Spalding,None,None,None,None,mcmuj101,John McMullin,spala101,Al Spalding,flync101,Clipper Flynn,9.0,mcgem101,Mike McGeary,2.0,yorkt101,Tom York,8.0,mcmuj101,John McMullin,1.0,kings101,Steve King,7.0,beave101,Edward Beavens,4.0,bells101,Steve Bellan,5.0,pikel101,Lip Pike,3.0,cravb101,Bill Craver,6.0,barnr102,Ross Barnes,4.0,birdd102,Dave Birdsall,9.0,mcvec101,Cal McVey,2.0,wrigh101,Harry Wright,6.0,goulc101,Charlie Gould,3.0,schah101,Harry Schafer,5.0,conef101,Fred Cone,7.0,spala101,Al Spalding,1.0,jacks101,Sam Jackson,8.0,HTBF,Y,BS1187105160

EinfÃ¼gen eines primary keys bestehend aus
Name des home teams, Datum, Nr. des Spiels.

In [25]:
run_query("select h_name||date||number_of_game from game_log limit 5")

  h_name||date||number_of_game
0                 FW1187105040
1                 WS3187105050
2                 RC1187105060
3                 CH1187105080
4                 TRO187105090

In [26]:
run_command("update game_log set game_id=h_name||date||number_of_game")

In [27]:
run_query("select * from game_log limit 5")

,date,number_of_game,day_of_week,v_name,v_league,v_game_number,h_name,h_league,h_game_number,v_score,h_score,length_outs,day_night,completion,forefeit,protest,park_id,attendance,length_minutes,v_line_score,h_line_score,v_at_bats,v_hits,v_doubles,v_triples,v_homeruns,v_rbi,v_sacrifice_hits,v_sacrifice_flies,v_hit_by_pitch,v_walks,v_intentional_walks,v_strikeouts,v_stolen_bases,v_caught_stealing,v_grounded_into_double,v_first_catcher_interference,v_left_on_base,v_pitchers_used,v_individual_earned_runs,v_team_earned_runs,v_wild_pitches,v_balks,v_putouts,v_assists,v_errors,v_passed_balls,v_double_plays,v_triple_plays,h_at_bats,h_hits,h_doubles,h_triples,h_homeruns,h_rbi,h_sacrifice_hits,h_sacrifice_flies,h_hit_by_pitch,h_walks,h_intentional_walks,h_strikeouts,h_stolen_bases,h_caught_stealing,h_grounded_into_double,h_first_catcher_interference,h_left_on_base,h_pitchers_used,h_individual_earned_runs,h_team_earned_runs,h_wild_pitches,h_balks,h_putouts,h_assists,h_errors,h_passed_balls,h_double_plays,h_triple_plays,hp_umpire_id,hp_umpire_name,1b_umpire_id,1b_umpire_name,2b_umpire_id,2b_umpire_name,3b_umpire_id,3b_umpire_name,lf_umpire_id,lf_umpire_name,rf_umpire_id,rf_umpire_name,v_manager_id,v_manager_name,h_manager_id,h_manager_name,winning_pitcher_id,winning_pitcher_name,losing_pitcher_id,losing_pitcher_name,saving_pitcher_id,saving_pitcher_name,winning_rbi_batter_id,winning_rbi_batter_id_name,v_starting_pitcher_id,v_starting_pitcher_name,h_starting_pitcher_id,h_starting_pitcher_name,v_player_1_id,v_player_1_name,v_player_1_def_pos,v_player_2_id,v_player_2_name,v_player_2_def_pos,v_player_3_id,v_player_3_name,v_player_3_def_pos,v_player_4_id,v_player_4_name,v_player_4_def_pos,v_player_5_id,v_player_5_name,v_player_5_def_pos,v_player_6_id,v_player_6_name,v_player_6_def_pos,v_player_7_id,v_player_7_name,v_player_7_def_pos,v_player_8_id,v_player_8_name,v_player_8_def_pos,v_player_9_id,v_player_9_name,v_player_9_def_pos,h_player_1_id,h_player_1_name,h_player_1_def_pos,h_player_2_id,h_player_2_name,h_player_2_def_pos,h_player_3_id,h_player_3_name,h_player_3_def_pos,h_player_4_id,h_player_4_name,h_player_4_def_pos,h_player_5_id,h_player_5_name,h_player_5_def_pos,h_player_6_id,h_player_6_name,h_player_6_def_pos,h_player_7_id,h_player_7_name,h_player_7_def_pos,h_player_8_id,h_player_8_name,h_player_8_def_pos,h_player_9_id,h_player_9_name,h_player_9_def_pos,additional_info,acquisition_info,game_id
0,18710504,0,Thu,CL1,None,1,FW1,None,1,0,2,54.0,D,None,None,None,FOR01,200.0,120.0,000000000,010010000,30.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,None,6.0,1.0,None,-1.0,None,4.0,1.0,1.0,1.0,0.0,0.0,27.0,9.0,0.0,3.0,0.0,0.0,31.0,4.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,None,0.0,0.0,None,-1.0,None,3.0,1.0,0.0,0.0,0.0,0.0,27.0,3.0,3.0,1.0,1.0,0.0,boakj901,John Boake,None,None,None,None,None,None,None,None,None,None,paboc101,Charlie Pabor,lennb101,Bill Lennon,mathb101,Bobby Mathews,prata101,Al Pratt,None,None,None,None,prata101,Al Pratt,mathb101,Bobby Mathews,whitd102,Deacon White,2.0,kimbg101,Gene Kimball,4.0,paboc101,Charlie Pabor,7.0,allia101,Art Allison,8.0,white104,Elmer White,9.0,prata101,Al Pratt,1.0,sutte101,Ezra Sutton,5.0,carlj102,Jim Carleton,3.0,bassj101,John Bass,6.0,selmf101,Frank Sellman,5.0,mathb101,Bobby Mathews,1.0,foraj101,Jim Foran,3.0,goldw101,Wally Goldsmith,6.0,lennb101,Bill Lennon,2.0,caret101,Tom Carey,4.0,mince101,Ed Mincher,7.0,mcdej101,James McDermott,8.0,kellb105,Bill Kelly,9.0,None,Y,FW1187105040
1,18710505,0,Fri,BS1,None,1,WS3,None,1,20,18,54.0,D,None,None,None,WAS01,5000.0,145.0,107000435,640113030,41.0,13.0,1.0,2.0,0.0,13.0,0.0,0.0,0.0,18.0,None,5.0,3.0,None,-1.0,None,12.0,1.0,6.0,6.0,1.0,0.0,27.0,13.0,10.0,1.0,2.0,0.0,49.0,14.0,2.0,0.0,0.0,11.0,0.0,0.0,0.0,10.0,None,2.0,1.0,None,-1.0,None,14.0,1.0,7.0,7.0,0.0,0.0,27.0,20.0,10.0,2.0,3.0,0.0,dobsh901,Henry Dobson,None,None,None,None,None,None,None,None,None,None,wrigh101,Harry Wright,younn801,Nick Young,spala101,Al Spalding,braia102,Asa Brainard,None,None,None,None,spala101,Al Spalding,braia102,Asa Brainard,wrigg101,George Wright,6.0,barnr102,Ross Barnes,4.0,birdd102,Dave Birdsall,9.0,mcvec101,Cal McVey,2.0,wrigh101,Harry Wright,8.0,goulc101,Charlie Gould,3.0,schah101,Harry Schafer,5.0,conef101,Fred Cone,7.0,spala101,Al Spalding,1.0,watef102,Fred Waterman,5.0,forcd101,Davy Force,6.0,mille105,Everett Mills,3.0,allid101,Doug Allison,2.0,hallg101,George Hall,7.0,leona101,Andy Leonard,4.0,braia102,Asa Brainard,1.0,burrh101,Henry Burroughs,9.0,berth101,Henry Berthrong,8.0,HTBF,Y,WS3187105050
2,18710506,0,Sat,CL1,None,2,RC1,None,1,12,4,54.0,D,None,None,None,RCK01,1000.0,140.0,610020003,010020100,49.0,11.0,1.0,1.0,0.0,8.0,0.0,0.0,0.0,0.0,None,1.0,0.0,None,-1.0,None,10.0,1.0,0.0,0.0,2.0,0.0,27.0,12.0,8.0,5.0,0.0,0.0,36.0,7.0,2.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,None,3.0,5.0,None,-1.0,None,5.0,1.0,3.0,3.0,1.0,0.0,27.0,12.0,13.0,3.0,0.0,0.0,mawnj901,J.H. Manny,None,None,None,None,None,None,None,None,None,None,paboc101,Charlie Pabor,hasts101,Scott Hastings,prata101,Al Pratt,fishc102,Cherokee Fisher,None,None,None,None,prata101,Al Pratt,fishc102,Cherokee Fisher,whitd102,Deacon White,2.0,kimbg101,Gene Kimball,4.0,paboc101,Charlie Pabor,7.0,allia101,Art Allison,8.0,white104,Elmer White,9.0,prata101,Al Pratt,1.0,sutte101,Ezra Sutton,5.0,carlj102,Jim Carleton,3.0,bassj101,John Bass,6.0,mackd101,Denny Mack,3.0,addyb101,Bob Addy,4.0,fishc102,Cherokee Fisher,1.0,hasts101,Scott Hastings,8.0,ham-r101,Ralph Ham,5.0,ansoc101,Cap Anson,2.0,sagep101,Pony Sager,6.0,birdg101,George Bird,7.0,stirg101,Gat Stires,9.0,None,Y,RC1187105060
3,18710508,0,Mon,CL1,None,3,CH1,None,1,12,14,54.0,D,None,None,None,CHI01,5000.0,150.0,101403111,077000000,46.0,15.0,2.0,1.0,2.0,10.0,0.0,0.0,0.0,0.0,None,1.0,0.0,None,-1.0,None,7.0,1.0,6.0,6.0,0.0,0.0,27.0,15.0,11.0,6.0,0.0,0.0,43.0,11.0,2.0,0.0,0.0,8.0,0.0,0.0,0.0,4.0,None,2.0,1.0,None,-1.0,None,6.0,1.0,4.0,4.0,0.0,0.0,27.0,14.0,7.0,2.0,0.0,0.0,willg901,Gardner Willard,None,None,None,None,None,None,None,None,None,None,paboc101,Charlie Pabor,woodj106,Jimmy Wood,zettg101,George Zettlein,prata101,Al Pratt,None,None,None,None,prata101,Al Pratt,zettg101,George Zettlein,whitd102,Deacon White,2.0,kimbg101,Gene Kimball,4.0,paboc101,Charlie Pabor,7.0,allia101,Art Allison,8.0,white104,Elmer White,9.0,prata101,Al Pratt,1.0,sutte101,Ezra Sutton,5.0,carlj102,Jim Carleton,3.0,bassj101,John Bass,6.0,mcatb101,Bub McAtee,3.0,kingm101,Marshall King,8.0,hodec101,Charlie Hodes,2.0,woodj106,Jimmy Wood,4.0,simmj101,Joe Simmons,9.0,folet101,Tom Foley,7.0,duffe101,Ed Duffy,6.0,pinke101,Ed Pinkham,5.0,zettg101,George Zettlein,1.0,None,Y,CH1187105080
4,18710509,0,Tue,BS1,None,2,TRO,None,1,9,5,54.0,D,None,None,None,TRO01,3250.0,145.0,000002232,101003000,46.0,17.0,4.0,1.0,0.0,6.0,0.0,0.0,0.0,2.0,None,0.0,1.0,None,-1.0,None,12.0,1.0,2.0,2.0,0.0,0.0,27.0,12.0,5.0,0.0,1.0,0.0,36.0,9.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,3.0,None,0.0,2.0,None,-1.0,None,7.0,1.0,3.0,3.0,1.0,0.0,27.0,11.0,7.0,3.0,0.0,0.0,leroi901,Isaac Leroy,None,None,None,None,None,None,None,None,None,None,wrigh101,Harry Wright,pikel101,Lip Pike,spala101,Al Spalding,mcmuj101,John McMullin,None,None,None,None,spala101,Al Spalding,mcmuj101,John McMullin,wrigg101,George Wright,6.0,barnr102,Ross Barnes,4.0,birdd102,Dave Birdsall,9.0,mcvec101,Cal McVey,2.0,wrigh101,Harry Wright,8.0,goulc101,Charlie Gould,3.0,schah101,Harry Schafer,5.0,conef101,Fred Cone,7.0,spala101,Al Spalding,1.0,flync101,Clipper Flynn,9.0,mcgem101,Mike McGeary,2.0,yorkt101,Tom York,8.0,mcmuj101,John McMullin,1.0,kings101,Steve King,7.0,beave101,Edward Beavens,4.0,bells101,Steve Bellan,5.0,pikel101,Lip Pike,3.0,cravb101,Bill Craver,6.0,HTBF,Y,TRO187105090

In [28]:
#park_codes.to_sql("park_codes",sql.connect("mlb.db"),index=False)

In [29]:
run_query("select * from park_codes limit 2")

,park_id,name,aka,city,state,start,end,league,notes
0,ALB01,Riverside Park,None,Albany,NY,09/11/1880,05/30/1882,NL,TRN:9/11/80;6/15&9/10/1881;5/16-5/18&5/30/1882
1,ALT01,Columbia Park,None,Altoona,PA,04/30/1884,05/31/1884,UA,None

In [30]:
#person_codes.to_sql("person_codes",sql.connect("mlb.db"),index=False)

In [31]:
run_query("select * from person_codes limit 2")

         id     last  first player_debut mgr_debut coach_debut ump_debut
0  aardd001  Aardsma  David   04/06/2004      None        None      None
1  aaroh101    Aaron   Hank   04/13/1954      None        None      None

In [32]:
#team_codes.to_sql("team_codes",sql.connect("mlb.db"),index=False)

In [33]:
run_query("select * from team_codes limit 2")

  team_id league  start   end     city         nickname franch_id  seq
0     ALT     UA   1884  1884  Altoona  Mountain Cities       ALT    1
1     ARI     NL   1998     0  Arizona     Diamondbacks       ARI    1

# Datenbank nach Schema normalisieren

![Database](https://i.imgur.com/FLgRzWw.png)

In [34]:
#run_command("create table person (person_id text primary key, first_name text, last_name text)")

In [35]:
run_query("select * from person limit 2")

  person_id first_name last_name
0  aardd001      David   Aardsma
1  aaroh101       Hank     Aaron

In [36]:
#run_command("insert into person select id,first,last from person_codes")

In [37]:
run_query("select * from person limit 2")

  person_id first_name last_name
0  aardd001      David   Aardsma
1  aaroh101       Hank     Aaron

In [38]:
#run_command("create table park (park_id text primary key, name text, nickname text, city text, state text, notes text)")

In [39]:
run_query("select * from park limit 2")

,park_id,name,nickname,city,state,notes
0,ALB01,Riverside Park,None,Albany,NY,TRN:9/11/80;6/15&9/10/1881;5/16-5/18&5/30/1882
1,ALT01,Columbia Park,None,Altoona,PA,None

In [40]:
park_codes.head(2)

,park_id,name,aka,city,state,start,end,league,notes
0,ALB01,Riverside Park,NaN,Albany,NY,09/11/1880,05/30/1882,NL,TRN:9/11/80;6/15&9/10/1881;5/16-5/18&5/30/1882
1,ALT01,Columbia Park,NaN,Altoona,PA,04/30/1884,05/31/1884,UA,NaN

In [41]:
#run_command("insert into park select park_id, name, aka, city, state, notes from park_codes")

In [42]:
run_query("select * from park limit 2")

,park_id,name,nickname,city,state,notes
0,ALB01,Riverside Park,None,Albany,NY,TRN:9/11/80;6/15&9/10/1881;5/16-5/18&5/30/1882
1,ALT01,Columbia Park,None,Altoona,PA,None

In [43]:
#run_command("create table league (league_id text primary key, name text)")

In [44]:
#run_command("insert into league (league_id, name) values ('NL', 'National League'), ('UA', 'Union Association'),('AL', 'American League'),('PL', 'Player''s League'),('FL', 'Federal League'),('AA', 'American Association');")

In [45]:
run_query("select * from league")

  league_id                  name
0        NL       National League
1        UA     Union Association
2        AL       American League
3        PL       Player's League
4        FL        Federal League
5        AA  American Association

In [47]:
#pd.read_csv("appearance_type.csv").to_sql("appearance_type_raw",sql.connect("mlb.db"),index=False)

In [48]:
run_query("select * from appearance_type_raw limit 5")

  appearance_type_id      name category
0                 O1  Batter 1  offense
1                 O2  Batter 2  offense
2                 O3  Batter 3  offense
3                 O4  Batter 4  offense
4                 O5  Batter 5  offense

In [49]:
#run_command("create table appearance_type (appearance_type_id text primary key, name text, category text)")

In [50]:
run_query("select * from appearance_type limit 5")

  appearance_type_id      name category
0                 O1  Batter 1  offense
1                 O2  Batter 2  offense
2                 O3  Batter 3  offense
3                 O4  Batter 4  offense
4                 O5  Batter 5  offense

In [51]:
#run_command("insert into appearance_type select * from appearance_type_raw")

In [52]:
run_query("select * from appearance_type limit 5")

  appearance_type_id      name category
0                 O1  Batter 1  offense
1                 O2  Batter 2  offense
2                 O3  Batter 3  offense
3                 O4  Batter 4  offense
4                 O5  Batter 5  offense

In an earlier mission, we discussed in passing that by default, SQLite doesn't enforce foreign key relationships. To ensure the integrity of our data, we need to make sure we enable it after each time we create a sqlite3 connection object in python.

In [53]:
def run_command(c):
    with sql.connect("mlb.db") as conn:
        conn.execute('PRAGMA foreign_keys = ON;')
        conn.isolation_level = None
        conn.execute(c)

In [54]:
run_query("select name from sqlite_master where type='table'")

                   name
0              game_log
1            park_codes
2          person_codes
3            team_codes
4                person
5                  park
6                league
7       appearance_type
8                  team
9                  game
10      team_appearance
11  appearance_type_raw
12    person_appearance

In [55]:
run_query("select * from team_codes limit 1")

  team_id league  start   end     city         nickname franch_id  seq
0     ALT     UA   1884  1884  Altoona  Mountain Cities       ALT    1

In [56]:
#run_command("create table team (team_id text primary key,league_id text, city text, nickname text, franch_id text, foreign key(league_id) references league(league_id))")

In [57]:
run_query("select * from team limit 1")

  team_id league_id     city         nickname franch_id
0     ALT        UA  Altoona  Mountain Cities       ALT

In [58]:
#run_command("insert into team select team_id, league, city, nickname, franch_id from team_codes group by team_id")

In [59]:
run_query("select * from team limit 5")

  team_id league_id       city         nickname franch_id
0     ALT        UA    Altoona  Mountain Cities       ALT
1     ANA        AL    Anaheim           Angels       LAA
2     ARI        NL    Arizona     Diamondbacks       ARI
3     ATL        NL    Atlanta           Braves       BS1
4     BAL        AL  Baltimore          Orioles       MLA

Ohne Gruppierungsanweisung gab es einen Unique Constraint Fehler. Dies weiÃŸt auf Redundanz im Datensatz "team_id" hin. Dies wird genauer untersucht.

In [60]:
team_codes["team_id"].value_counts()

MIL    2
PTU    1
LAA    1
CAL    1
TL2    1
CHP    1
LS3    1
CL1    1
MIN    1
NEW    1
IND    1
CN1    1
PRO    1
PTF    1
WOR    1
CL2    1
PH3    1
BRP    1
CN2    1
WAS    1
WS1    1
CNU    1
LAN    1
CLE    1
NY4    1
WSN    1
BL4    1
BLN    1
TRO    1
TL1    1
ANA    1
BLU    1
CIN    1
BOS    1
CH2    1
FW1    1
FLO    1
OAK    1
RC1    1
DET    1
SE1    1
BS2    1
KCF    1
SL4    1
CN3    1
PTP    1
SR1    1
PH4    1
IN2    1
DTN    1
BL2    1
KCN    1
MIA    1
WS8    1
HAR    1
BRO    1
WIL    1
CHU    1
HOU    1
IN3    1
BLF    1
BSU    1
NH1    1
CL5    1
NY1    1
MLA    1
SEA    1
RC2    1
SDN    1
BR4    1
LS2    1
BFP    1
ALT    1
ARI    1
SFN    1
CL3    1
CL4    1
BR1    1
NY2    1
KC2    1
PHN    1
PT1    1
ATL    1
MON    1
PH2    1
KC1    1
BFN    1
IN1    1
MID    1
WS6    1
PH1    1
PIT    1
ML2    1
WS2    1
CHN    1
LS1    1
BAL    1
CHF    1
WS9    1
WS3    1
NY3    1
BSN    1
WS7    1
ELI    1
SLU    1
SLN    1
WS4    1
BSP    1
ML3    1
SLF    1
BUF    1
BRF    1
CL6    1
WSU    1
RIC    1
SLA    1
SL2    1
SL5    1
BS1    1
COL    1
TOR    1
TBA    1
SL1    1
PHP    1
NYA    1
SL3    1
CH1    1
KCA    1
WS5    1
HR1    1
PHU    1
KCU    1
TRN    1
PHA    1
CHA    1
NYN    1
SPU    1
SR2    1
CLP    1
BR2    1
MLN    1
KEO    1
TEX    1
PHI    1
BL1    1
MLU    1
NYP    1
BLA    1
BR3    1
Name: team_id, dtype: int64

In [61]:
team_codes.loc[team_codes["team_id"]=="MIL",:]

    team_id league  start   end       city nickname franch_id  seq
112     MIL     AL   1970  1997  Milwaukee  Brewers       SE1    2
113     MIL     NL   1998     0  Milwaukee  Brewers       SE1    3

Es sieht so aus, als ob es die "Milwaukee Brewes" in der Geschichte zweimal gegeben hat. Einmal von 1970 bis 1997 und einmal seit 1998. Der Hauptunterschied scheint in einer Unterschiedlichen Liga zu liegen, in welcher das Team jeweils teillnahm.

In [62]:
run_query("select * from team where team_id='MIL'")

  team_id league_id       city nickname franch_id
0     MIL        NL  Milwaukee  Brewers       SE1

Das aktuelle Team wurde Ã¼bernommen. WeiterfÃ¼hren dieser Zuordnung bedeutet Datenverlust. WÃ¤re dies keine Ãœbung wÃ¼rde ich vorschlagen, die team_id zu Ã¤ndern.

In [63]:
#run_command("create table game (game_id text primary key,date date, number_of_game integer, park_id text, length_outs real, day boolean, completion text, forfeit text, protest text, attendance integer, length_minutes integer, additional_info text, acquisition_info text, foreign key(park_id) references park(park_id))")

In [64]:
run_query("select * from game limit 10")

,game_id,date,number_of_game,park_id,length_outs,day,completion,forfeit,protest,attendance,length_minutes,additional_info,acquisition_info
0,FW1187105040,18710504,0,FOR01,54.0,D,None,None,None,200.0,120.0,None,Y
1,WS3187105050,18710505,0,WAS01,54.0,D,None,None,None,5000.0,145.0,HTBF,Y
2,RC1187105060,18710506,0,RCK01,54.0,D,None,None,None,1000.0,140.0,None,Y
3,CH1187105080,18710508,0,CHI01,54.0,D,None,None,None,5000.0,150.0,None,Y
4,TRO187105090,18710509,0,TRO01,54.0,D,None,None,None,3250.0,145.0,HTBF,Y
5,CL1187105110,18710511,0,CLE01,48.0,D,None,V,None,2500.0,120.0,None,Y
6,CL1187105130,18710513,0,CIN01,54.0,D,None,None,None,1200.0,150.0,None,Y
7,FW1187105130,18710513,0,FOR01,54.0,D,None,None,None,1500.0,105.0,None,Y
8,FW1187105150,18710515,0,FOR01,54.0,D,None,None,None,NaN,140.0,None,Y
9,BS1187105160,18710516,0,BOS01,54.0,D,None,None,None,2500.0,NaN,HTBF,Y

In [65]:
#run_command("insert into game select game_id, date, number_of_game, park_id, length_outs, day_night day, completion, forefeit, protest, attendance, length_minutes, additional_info, acquisition_info from game_log")

In [66]:
run_query("select * from game limit 10")

,game_id,date,number_of_game,park_id,length_outs,day,completion,forfeit,protest,attendance,length_minutes,additional_info,acquisition_info
0,FW1187105040,18710504,0,FOR01,54.0,D,None,None,None,200.0,120.0,None,Y
1,WS3187105050,18710505,0,WAS01,54.0,D,None,None,None,5000.0,145.0,HTBF,Y
2,RC1187105060,18710506,0,RCK01,54.0,D,None,None,None,1000.0,140.0,None,Y
3,CH1187105080,18710508,0,CHI01,54.0,D,None,None,None,5000.0,150.0,None,Y
4,TRO187105090,18710509,0,TRO01,54.0,D,None,None,None,3250.0,145.0,HTBF,Y
5,CL1187105110,18710511,0,CLE01,48.0,D,None,V,None,2500.0,120.0,None,Y
6,CL1187105130,18710513,0,CIN01,54.0,D,None,None,None,1200.0,150.0,None,Y
7,FW1187105130,18710513,0,FOR01,54.0,D,None,None,None,1500.0,105.0,None,Y
8,FW1187105150,18710515,0,FOR01,54.0,D,None,None,None,NaN,140.0,None,Y
9,BS1187105160,18710516,0,BOS01,54.0,D,None,None,None,2500.0,NaN,HTBF,Y

In [67]:
run_query("select sql from sqlite_master where name='game_log' and type='table'")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      sql
0  CREATE TABLE "game_log" (\n"date" INTEGER,\n  "number_of_game" INTEGER,\n  "day_of_week" TEXT,\n  "v_name" TEXT,\n  "v_league" TEXT,\n  "v_game_number" INTEGER,\n  "h_name" TEXT,\n  "h_league" TEXT,\n  "h_game_number" INTEGER,\n  "v_score" INTEGER,\n  "h_score" INTEGER,\n  "length_outs" REAL,\n  "day_night" TEXT,\n  "completion" TEXT,\n  "forefeit" TEXT,\n  "protest" TEXT,\n  "park_id" TEXT,\n  "attendance" REAL,\n  "length_minutes" REAL,\n  "v_line_score" TEXT,\n  "h_line_score" TEXT,\n  "v_at_bats" REAL,\n  "v_hits" REAL,\n  "v_doubles" REAL,\n  "v_triples" REAL,\n  "v_homeruns" REAL,\n  "v_rbi" REAL,\n  "v_sacrifice_hits" REAL,\n  "v_sacrifice_flies" REAL,\n  "v_hit_by_pitch" REAL,\n  "v_walks" REAL,\n  "v_intentional_walks" REAL,\n  "v_strikeouts" REAL,\n  "v_stolen_bases" REAL,\n  "v_caught_stealing" REAL,\n  "v_grounded_into_double" REAL,\n  "v_first_catcher_interference" REAL,\n  "v_left_on_base" REAL,\n  "v_pitchers_used" REAL,\n  "v_individual_earned_runs" REAL,\n  "v_team_earned_runs" REAL,\n  "v_wild_pitches" REAL,\n  "v_balks" REAL,\n  "v_putouts" REAL,\n  "v_assists" REAL,\n  "v_errors" REAL,\n  "v_passed_balls" REAL,\n  "v_double_plays" REAL,\n  "v_triple_plays" REAL,\n  "h_at_bats" REAL,\n  "h_hits" REAL,\n  "h_doubles" REAL,\n  "h_triples" REAL,\n  "h_homeruns" REAL,\n  "h_rbi" REAL,\n  "h_sacrifice_hits" REAL,\n  "h_sacrifice_flies" REAL,\n  "h_hit_by_pitch" REAL,\n  "h_walks" REAL,\n  "h_intentional_walks" REAL,\n  "h_strikeouts" REAL,\n  "h_stolen_bases" REAL,\n  "h_caught_stealing" REAL,\n  "h_grounded_into_double" REAL,\n  "h_first_catcher_interference" REAL,\n  "h_left_on_base" REAL,\n  "h_pitchers_used" REAL,\n  "h_individual_earned_runs" REAL,\n  "h_team_earned_runs" REAL,\n  "h_wild_pitches" REAL,\n  "h_balks" REAL,\n  "h_putouts" REAL,\n  "h_assists" REAL,\n  "h_errors" REAL,\n  "h_passed_balls" REAL,\n  "h_double_plays" REAL,\n  "h_triple_plays" REAL,\n  "hp_umpire_id" TEXT,\n  "hp_umpire_name" TEXT,\n  "1b_umpire_id" TEXT,\n  "1b_umpire_name" TEXT,\n  "2b_umpire_id" TEXT,\n  "2b_umpire_name" TEXT,\n  "3b_umpire_id" TEXT,\n  "3b_umpire_name" TEXT,\n  "lf_umpire_id" TEXT,\n  "lf_umpire_name" TEXT,\n  "rf_umpire_id" TEXT,\n  "rf_umpire_name" TEXT,\n  "v_manager_id" TEXT,\n  "v_manager_name" TEXT,\n  "h_manager_id" TEXT,\n  "h_manager_name" TEXT,\n  "winning_pitcher_id" TEXT,\n  "winning_pitcher_name" TEXT,\n  "losing_pitcher_id" TEXT,\n  "losing_pitcher_name" TEXT,\n  "saving_pitcher_id" TEXT,\n  "saving_pitcher_name" TEXT,\n  "winning_rbi_batter_id" TEXT,\n  "winning_rbi_batter_id_name" TEXT,\n  "v_starting_pitcher_id" TEXT,\n  "v_starting_pitcher_name" TEXT,\n  "h_starting_pitcher_id" TEXT,\n  "h_starting_pitcher_name" TEXT,\n  "v_player_1_id" TEXT,\n  "v_player_1_name" TEXT,\n  "v_player_1_def_pos" REAL,\n  "v_player_2_id" TEXT,\n  "v_player_2_name" TEXT,\n  "v_player_2_def_pos" REAL,\n  "v_player_3_id" TEXT,\n  "v_player_3_name" TEXT,\n  "v_player_3_def_pos" REAL,\n  "v_player_4_id" TEXT,\n  "v_player_4_name" TEXT,\n  "v_player_4_def_pos" REAL,\n  "v_player_5_id" TEXT,\n  "v_player_5_name" TEXT,\n  "v_player_5_def_pos" REAL,\n  "v_player_6_id" TEXT,\n  "v_player_6_name" TEXT,\n  "v_player_6_def_pos" REAL,\n  "v_player_7_id" TEXT,\n  "v_player_7_name" TEXT,\n  "v_player_7_def_pos" REAL,\n  "v_player_8_id" TEXT,\n  "v_player_8_name" TEXT,\n  "v_player_8_def_pos" REAL,\n  "v_player_9_id" TEXT,\n  "v_player_9_name" TEXT,\n  "v_player_9_def_pos" REAL,\n  "h_player_1_id" TEXT,\n  "h_player_1_name" TEXT,\n  "h_player_1_def_pos" REAL,\n  "h_player_2_id" TEXT,\n  "h_player_2_name" TEXT,\n  "h_player_2_def_pos" REAL,\n  "h_player_3_id" TEXT,\n  "h_player_3_name" TEXT,\n  "h_player_3_def_pos" REAL,\n  "h_player_4_id" TEXT,\n  "h_player_4_name" TEXT,\n  "h_player_4_def_pos" REAL,\n  "h_player_5_id" TEXT,\n  "h_player_5_name" TEXT,\n  "h_player_5_def_pos" REAL,\n  "h_player_6_id" TEXT,\n  "h_player_6_name" TEXT,\n  "h_player_6_def_pos" REAL,\n  "h_player_7_id" TEXT,\n  "h_player_7_name" TEXT,\n  "h_player_7_def_pos" REAL,\n  "h_player_8_id" TEXT,\n  "h_player_8_name" TEXT,\n  "h_player_8_def_pos" REAL,\n  "h_player_9_id" TEXT,\n  "h_player_9_name" TEXT,\n  "h_player_9_def_pos" REAL,\n  "additional_info" TEXT,\n  "acquisition_info" TEXT\n, game_id text)

In [68]:
#run_command("create table team_appearance (team_id text, game_id text,home boolean, league_id text, score integer, line_score text, at_bats integer, hits integer, doubles integer, triples integer, homeruns integer, rbi integer, sacrifice_hits real, sacrifice_flies real, hit_by_pitch REAL,walks REAL, intentional_walks REAL, strikeouts REAL,stolen_bases REAL,caught_stealing REAL,grounded_into_double,first_catcher_interference REAL,left_on_base REAL,pitchers_used REAL,individual_earned_runs REAL,team_earned_runs REAL,wild_pitches REAL,balks REAL,putouts REAL,assists REAL,errors REAL,passed_balls REAL,double_plays REAL,triple_plays REAL, primary key (team_id,game_id), foreign key (game_id) references game(game_id), foreign key (league_id) references league(league_id))")

In [69]:
run_query("select * from team_appearance limit 1")

,team_id,game_id,home,league_id,score,line_score,at_bats,hits,doubles,triples,homeruns,rbi,sacrifice_hits,sacrifice_flies,hit_by_pitch,walks,intentional_walks,strikeouts,stolen_bases,caught_stealing,grounded_into_double,first_catcher_interference,left_on_base,pitchers_used,individual_earned_runs,team_earned_runs,wild_pitches,balks,putouts,assists,errors,passed_balls,double_plays,triple_plays
0,None,None,0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [70]:
 '"h_at_bats" REAL,\n "h_hits" REAL,\n "h_doubles" REAL,\n "h_triples" REAL,\n "h_homeruns" REAL,\n "h_rbi" REAL,\n "h_sacrifice_hits" REAL,\n "h_sacrifice_flies" REAL,\n "h_hit_by_pitch" REAL,\n "h_walks" REAL,\n "h_intentional_walks" REAL,\n "h_strikeouts" REAL,\n "h_stolen_bases" REAL,\n "h_caught_stealing" REAL,\n "h_grounded_into_double" REAL,\n "h_first_catcher_interference" REAL,\n "h_left_on_base" REAL,\n "h_pitchers_used" REAL,\n "h_individual_earned_runs" REAL,\n "h_team_earned_runs" REAL,\n "h_wild_pitches" REAL,\n "h_balks" REAL,\n "h_putouts" REAL,\n "h_assists" REAL,\n "h_errors" REAL,\n "h_passed_balls" REAL,\n "h_double_plays" REAL,\n "h_triple_plays" REAL'.replace ("\"","").replace("\n","").replace("REAL","").strip()

'h_at_bats , h_hits , h_doubles , h_triples , h_homeruns , h_rbi , h_sacrifice_hits , h_sacrifice_flies , h_hit_by_pitch , h_walks , h_intentional_walks , h_strikeouts , h_stolen_bases , h_caught_stealing , h_grounded_into_double , h_first_catcher_interference , h_left_on_base , h_pitchers_used , h_individual_earned_runs , h_team_earned_runs , h_wild_pitches , h_balks , h_putouts , h_assists , h_errors , h_passed_balls , h_double_plays , h_triple_plays'

In [71]:
 '"v_at_bats" REAL,\n "v_hits" REAL,\n "v_doubles" REAL,\n "v_triples" REAL,\n "v_homeruns" REAL,\n "v_rbi" REAL,\n "v_sacrifice_hits" REAL,\n "v_sacrifice_flies" REAL,\n "v_hit_by_pitch" REAL,\n "v_walks" REAL,\n "v_intentional_walks" REAL,\n "v_strikeouts" REAL,\n "v_stolen_bases" REAL,\n "v_caught_stealing" REAL,\n "v_grounded_into_double" REAL,\n "v_first_catcher_interference" REAL,\n "v_left_on_base" REAL,\n "v_pitchers_used" REAL,\n "v_individual_earned_runs" REAL,\n "v_team_earned_runs" REAL,\n "v_wild_pitches" REAL,\n "v_balks" REAL,\n "v_putouts" REAL,\n "v_assists" REAL,\n "v_errors" REAL,\n "v_passed_balls" REAL,\n "v_double_plays" REAL,\n "v_triple_plays"'.replace ("\"","").replace("\n","").replace("REAL","").strip()

'v_at_bats , v_hits , v_doubles , v_triples , v_homeruns , v_rbi , v_sacrifice_hits , v_sacrifice_flies , v_hit_by_pitch , v_walks , v_intentional_walks , v_strikeouts , v_stolen_bases , v_caught_stealing , v_grounded_into_double , v_first_catcher_interference , v_left_on_base , v_pitchers_used , v_individual_earned_runs , v_team_earned_runs , v_wild_pitches , v_balks , v_putouts , v_assists , v_errors , v_passed_balls , v_double_plays , v_triple_plays'

Und ein mit ein bisschen Copy&Paste:

In [72]:
#run_command("insert into team_appearance select h_name, game_id, 1 AS home, h_league, h_score, h_line_score, h_at_bats , h_hits , h_doubles , h_triples , h_homeruns , h_rbi , h_sacrifice_hits , h_sacrifice_flies , h_hit_by_pitch , h_walks , h_intentional_walks , h_strikeouts , h_stolen_bases , h_caught_stealing , h_grounded_into_double , h_first_catcher_interference , h_left_on_base , h_pitchers_used , h_individual_earned_runs , h_team_earned_runs , h_wild_pitches , h_balks , h_putouts , h_assists , h_errors , h_passed_balls , h_double_plays , h_triple_plays from game_log union select v_name, game_id, 0 as home, v_league, v_score, v_line_score, v_at_bats , v_hits , v_doubles , v_triples , v_homeruns , v_rbi , v_sacrifice_hits , v_sacrifice_flies , v_hit_by_pitch , v_walks , v_intentional_walks , v_strikeouts , v_stolen_bases , v_caught_stealing , v_grounded_into_double , v_first_catcher_interference , v_left_on_base , v_pitchers_used , v_individual_earned_runs , v_team_earned_runs , v_wild_pitches , v_balks , v_putouts , v_assists , v_errors , v_passed_balls , v_double_plays , v_triple_plays from game_log;")

In [73]:
run_query("select * from team_appearance limit 50")

,team_id,game_id,home,league_id,score,line_score,at_bats,hits,doubles,triples,homeruns,rbi,sacrifice_hits,sacrifice_flies,hit_by_pitch,walks,intentional_walks,strikeouts,stolen_bases,caught_stealing,grounded_into_double,first_catcher_interference,left_on_base,pitchers_used,individual_earned_runs,team_earned_runs,wild_pitches,balks,putouts,assists,errors,passed_balls,double_plays,triple_plays
0,None,None,0,None,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,None,None,1,None,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ALT,ALT188404300,1,UA,2.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ALT,ALT188405020,1,UA,3.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ALT,ALT188405030,1,UA,5.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ALT,ALT188405050,1,UA,2.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,ALT,ALT188405100,1,UA,9.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ALT,ALT188405120,1,UA,3.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,ALT,ALT188405140,1,UA,2.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,ALT,ALT188405150,1,UA,7.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,ALT,ALT188405160,1,UA,6.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,ALT,ALT188405170,1,UA,8.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,ALT,ALT188405210,1,UA,3.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,ALT,ALT188405230,1,UA,8.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,ALT,ALT188405240,1,UA,3.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,ALT,ALT188405260,1,UA,6.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,ALT,ALT188405270,1,UA,3.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,ALT,ALT188405290,1,UA,0.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,ALT,ALT188405300,1,UA,0.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,ALT,ALT188405310,1,UA,3.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,ALT,CNU188404170,0,UA,2.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,ALT,CNU188404180,0,UA,2.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,ALT,CNU188404190,0,UA,6.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,ALT,SLU188404240,0,UA,2.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,ALT,SLU188404260,0,UA,3.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,ALT,SLU188404270,0,UA,1.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,ALT,SLU188404280,0,UA,1.0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,ANA,ANA200004030,1,AL,2.0,010000001,35.0,10.0,1.0,0.0,1.0,2.0,0.0,0.0,0.0,5.0,0.0,6.0,0.0,1.0,0.0,0.0,11.0,3.0,3.0,3.0,0.0,0.0,27.0,16.0,1.0,0.0,0.0,0.0
28,ANA,ANA200004040,1,AL,3.0,000003000,36.0,10.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,6.0,0.0,9.0,1.0,0.0,2.0,0.0,12.0,4.0,5.0,5.0,0.0,0.0,27.0,12.0,1.0,0.0,2.0,0.0
29,ANA,ANA200004050,1,AL,12.0,12610110x,33.0,12.0,4.0,0.0,1.0,12.0,0.0,2.0,1.0,8.0,0.0,4.0,1.0,0.0,0.0,0.0,8.0,3.0,6.0,6.0,0.0,0.0,27.0,13.0,2.0,0.0,2.0,0.0
30,ANA,ANA200004070,1,AL,7.0,30000310x,32.0,9.0,2.0,0.0,2.0,7.0,1.0,0.0,0.0,5.0,2.0,5.0,3.0,0.0,0.0,0.0,7.0,2.0,3.0,3.0,0.0,0.0,27.0,9.0,0.0,0.0,1.0,0.0
31,ANA,ANA200004080,1,AL,7.0,20000401x,35.0,13.0,4.0,0.0,1.0,7.0,1.0,0.0,0.0,1.0,0.0,4.0,0.0,1.0,0.0,0.0,6.0,6.0,5.0,5.0,2.0,0.0,27.0,18.0,0.0,0.0,3.0,0.0
32,ANA,ANA200004090,1,AL,2.0,000000011,33.0,7.0,0.0,0.0,1.0,2.0,1.0,0.0,0.0,1.0,0.0,14.0,2.0,0.0,0.0,0.0,6.0,3.0,5.0,5.0,0.0,0.0,27.0,8.0,0.0,0.0,0.0,0.0
33,ANA,ANA200004100,1,AL,6.0,00200040x,28.0,7.0,2.0,0.0,1.0,6.0,0.0,1.0,0.0,9.0,1.0,1.0,0.0,0.0,1.0,0.0,8.0,1.0,0.0,0.0,2.0,0.0,27.0,17.0,1.0,0.0,2.0,0.0
34,ANA,ANA200004110,1,AL,5.0,04100000x,29.0,8.0,3.0,0.0,2.0,5.0,0.0,0.0,0.0,3.0,0.0,3.0,0.0,1.0,1.0,0.0,3.0,5.0,4.0,4.0,1.0,1.0,27.0,8.0,1.0,0.0,2.0,0.0
35,ANA,ANA200004120,1,AL,2.0,100010000,33.0,9.0,4.0,0.0,0.0,2.0,0.0,0.0,3.0,2.0,0.0,6.0,1.0,1.0,1.0,0.0,9.0,4.0,6.0,6.0,0.0,0.0,27.0,10.0,0.0,0.0,2.0,0.0
36,ANA,ANA200004240,1,AL,10.0,21121300x,35.0,14.0,2.0,0.0,4.0,10.0,1.0,0.0,0.0,3.0,0.0,1.0,0.0,0.0,2.0,0.0,5.0,3.0,3.0,3.0,1.0,0.0,27.0,13.0,2.0,0.0,2.0,0.0
37,ANA,ANA200004250,1,AL,2.0,002000000,34.0,8.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,5.0,0.0,5.0,0.0,0.0,1.0,0.0,10.0,2.0,2.0,2.0,0.0,0.0,27.0,10.0,2.0,0.0,2.0,0.0
38,ANA,ANA200004260,1,AL,6.0,03000012x,32.0,11.0,1.0,0.0,3.0,6.0,1.0,0.0,0.0,2.0,0.0,6.0,0.0,2.0,0.0,0.0,5.0,2.0,1.0,1.0,0.0,0.0,27.0,15.0,0.0,0.0,1.0,0.0
39,ANA,ANA200004270,1,AL,3.0,001000002,31.0,6.0,1.0,0.0,1.0,3.0,1.0,0.0,2.0,4.0,0.0,8.0,0.0,0.0,1.0,0.0,8.0,4.0,6.0,6.0,2.0,0.0,27.0,14.0,1.0,0.0,1.0,0.0
40,ANA,ANA200004280,1,AL,2.0,020000000,34.0,7.0,3.0,0.0,1.0,2.0,0.0,0.0,0.0,1.0,0.0,5.0,0.0,0.0,0.0,0.0,6.0,5.0,11.0,11.0,0.0,0.0,27.0,11.0,1.0,0.0,1.0,0.0
41,ANA,ANA200004290,1,AL,7.0,0101300010001,46.0,13.0,1.0,0.0,3.0,7.0,1.0,0.0,0.0,2.0,0.0,7.0,3.0,0.0,0.0,0.0,6.0,5.0,5.0,5.0,1.0,0.0,39.0,13.0,2.0,0.0,4.0,0.0
42,ANA,ANA200004300,1,AL,5.0,30010100x,32.0,9.0,1.0,0.0,1.0,5.0,0.0,0.0,0.0,3.0,0.0,9.0,0.0,0.0,1.0,0.0,6.0,3.0,2.0,2.0,0.0,0.0,27.0,5.0,0.0,0.0,0.0,0.0
43,ANA,ANA200005080,1,AL,9.0,12011310x,38.0,17.0,4.0,0.0,2.0,9.0,0.0,1.0,0.0,4.0,3.0,5.0,1.0,0.0,0.0,0.0,10.0,5.0,7.0,7.0,0.0,0.0,27.0,9.0,3.0,0.0,1.0,0.0
44,ANA,ANA200005090,1,AL,2.0,000000011,35.0,9.0,2.0,0.0,1.0,2.0,0.0,0.0,0.0,2.0,0.0,3.0,0.0,0.0,1.0,0.0,8.0,5.0,5.0,5.0,0.0,0.0,27.0,12.0,0.0,0.0,1.0,0.0
45,ANA,ANA200005100,1,AL,4.0,001000021,35.0,9.0,4.0,0.0,1.0,4.0,0.0,0.0,1.0,2.0,0.0,9.0,0.0,0.0,1.0,0.0,7.0,4.0,7.0,7.0,0.0,0.0,27.0,7.0,0.0,0.0,0.0,0.0
46,ANA,ANA200005110,1,AL,3.0,00001011x,32.0,10.0,1.0,0.0,2.0,3.0,1.0,0.0,0.0,1.0,1.0,5.0,0.0,0.0,1.0,0.0,7.0,5.0,2.0,2.0,0.0,0.0,27.0,11.0,0.0,0.0,1.0,0.0
47,ANA,ANA200005120,1,AL,11.0,210101123,40.0,14.0,2.0,0.0,5.0,11.0,0.0,0.0,0.0,5.0,0.0,7.0,2.0,1.0,0.0,0.0,7.0,2.0,13.0,13.0,0.0,0.0,27.0,15.0,0.0,0.0,2.0,0.0
48,ANA,ANA200005130,1,AL,5.0,100000211,30.0,7.0,2.0,0.0,1.0,5.0,0.0,3.0,0.0,6.0,0.0,3.0,0.0,0.0,2.0,0.0,7.0,4.0,6.0,6.0,0.0,0.0,27.0,11.0,2.0,0.0,0.0,0.0
49,ANA,ANA200005140,1,AL,7.0,202100002,32.0,8.0,2.0,0.0,5.0,7.0,0.0,0.0,0.0,2.0,0.0,6.0,0.0,1.0,0.0,0.0,2.0,5.0,6.0,6.0,0.0,0.0,27.0,11.0,1.0,0.0,0.0,0.0

In [74]:
game_log.shape[0]

171907

In [75]:
run_query("select count(*) from team_appearance")

   count(*)
0    343816

Zwei Ã¼berzÃ¤hlige Reihen sind erstellt worden. Dies ist merkwÃ¼rdig, allerdings liegt kein Datenverlust vor.

In [77]:
#run_command("create table person_appearance (appearance_id integer primary key, person_id text, team_id text, game_id text, appearance_type_id integer, foreign key(person_id) references person(person_id), foreign key(team_id) references team(team_id), foreign key(game_id) references game(game_id), foreign key(appearance_type_id) references appearance_type(appearance_type_id))")

In [78]:
run_query("select * from person_appearance limit 5")

Empty DataFrame
Columns: [appearance_id, person_id, team_id, game_id, appearance_type_id]
Index: []

In [101]:
run_command("insert into person_appearance (game_id,team_id,person_id,appearance_type_id) select game_id, NULL, lf_umpire_id, 'ULF' from game_log where lf_umpire_id is not NULL union select game_id, NULL, rf_umpire_id, 'URF' from game_log where rf_umpire_id is not NULL union select game_id, v_name, v_manager_id, 'MM' from game_log where v_manager_id is not null union select game_id, h_name, h_manager_id, 'MM' from game_log where h_manager_id is not null union select game_id, case when h_score > v_score then h_name else v_name end, winning_pitcher_id, 'AWP' from game_log where winning_pitcher_id is not null")

In [103]:
run_query("select * from person_appearance limit 10")

   appearance_id person_id team_id       game_id appearance_type_id
0              1  curte801     ALT  ALT188404300                 MM
1              2  sullt101     SLU  ALT188404300                 MM
2              3  curte801     ALT  ALT188405020                 MM
3              4  sullt101     SLU  ALT188405020                 MM
4              5  curte801     ALT  ALT188405030                 MM
5              6  sullt101     SLU  ALT188405030                 MM
6              7  curte801     ALT  ALT188405050                 MM
7              8  sullt101     SLU  ALT188405050                 MM
8              9  curte801     ALT  ALT188405100                 MM
9             10  murnt101     BSU  ALT188405100                 MM

Dieser Code ist verkÃ¼rzt und bildet nicht alle Positionen ab.